name: ros-jazzy-perception-tensorrt

services:
  default:
    build:
      context: "../../"
      dockerfile: "./jazzy/${COMPOSE_PROJECT_NAME}/Dockerfile"
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        USER_ID: ${USER_ID:-1000}
        USER: ${USER}
    network_mode: host
    ipc: host
    user: ${USER}
    stdin_open: true
    tty: true
    runtime: nvidia
    gpus: all

    # Environment variables are copied from host if they are set
    env_file:
      - "../../term.env"
      - "../../ros2.env"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - type: bind
        source: "./home"
        target: "${HOME}"
#      - type: bind
#        source: "/path/to/host/ros2_ws"
#        target: "${HOME}/ros2_ws"
