services:
  default:
    build:
      context: ../../
      dockerfile: ./jazzy/${COMPOSE_PROJECT_NAME}/Dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        USER_ID: ${USER_ID}
        USER: ${USER}
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

    # Environment variables are copied from host if they are set
    env_file:
      - "../../term.env"
      - "../../ros2.env"

    volumes:
      - type: bind
        source: ${HOST_HOME_PATH}
        target: ${HOME}
#      - type: bind
#        source: /path/to/host/ros2_ws
#        target: ${HOME}/ros2_ws
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
