services:
  default:
    build:
      context: ../../
      dockerfile: ./humble/${COMPOSE_PROJECT_NAME}/Dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        USER_ID: ${USER_ID}
        USER: ${USER}
    network_mode: host
    ipc: host
    user: ${USER}
    group_add:
      - video
    stdin_open: true
    tty: true
    runtime: nvidia
    gpus: all

    # Environment variables are copied from host if they are set
    env_file:
      - "../../term.env"
      - "../../ros2.env"
    environment:
      - DISPLAY
      - XAUTHORITY
      - XDG_RUNTIME_DIR
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri
    security_opt:
      - seccomp:unconfined

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:${XAUTHORITY}
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - type: bind
        source: ${HOST_HOME_PATH}
        target: ${HOME}
#      - type: bind
#        source: /path/to/host/ros2_ws
#        target: ${HOME}/ros2_ws
