services:
  default:
    build:
      context: ../../
      dockerfile: ./humble/${COMPOSE_PROJECT_NAME}/Dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        USER_ID: ${USER_ID}
        USER: ${USER}
    network_mode: host
    ipc: host
    user: ${USER}
    stdin_open: true
    tty: true
    runtime: nvidia
    gpus: all

    # Environment variables are copied from host if they are set
    env_file:
      - "../../term.env"
      - "../../ros2.env"

    volumes:
      - type: bind
        source: ${HOST_HOME_PATH}
        target: ${HOME}
#      - type: bind
#        source: /path/to/host/ros2_ws
#        target: ${HOME}/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${HOME}/.Xauthority
