name: ros-noetic-robot-avahi

services:
  default:
    build:
      context: "../../"
      dockerfile: "./noetic/${COMPOSE_PROJECT_NAME}/Dockerfile"
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        USER_ID: ${USER_ID}
        USER: ${USER}
    network_mode: host
    ipc: host
    user: ${USER}
    stdin_open: true
    tty: true

    # Environment variables are copied from host if they are set
    env_file:
      - "../../term.env"
      - "../../ros1.env"

    volumes:
      - "/var/run/dbus:/var/run/dbus"
      - "/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket"
      - type: bind
        source: "${HOST_HOME_DIR}"
        target: "${HOME}"
#      - type: bind
#        source: "/path/to/host/catkin_ws"
#        target: "${HOME}/catkin_ws"
